# Generated by Django 4.2.7 on 2023-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=30)),
                ('isActivate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('City_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('City_ID', models.IntegerField()),
                ('District_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Full_Contract',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_Contract_Code', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Year_Of_Birth', models.IntegerField()),
                ('SSN', models.CharField(max_length=15)),
                ('Customer_Address', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=15)),
                ('Property_ID', models.IntegerField()),
                ('Date_Of_Contract', models.DateField()),
                ('Price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Deposit', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Remain', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Installment_Contract',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Installment_Contract_Code', models.CharField(max_length=50)),
                ('Customer_Name', models.CharField(max_length=50)),
                ('Year_Of_Birth', models.IntegerField()),
                ('SSN', models.CharField(max_length=15)),
                ('Customer_Address', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=15)),
                ('Property_ID', models.IntegerField()),
                ('Date_Of_Contract', models.DateField()),
                ('Installment_Payment_Method', models.CharField(max_length=10)),
                ('Payment_Period', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Deposit', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Loan_Amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Taken', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Remain', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Property_Code', models.CharField(max_length=7)),
                ('Property_Name', models.CharField(max_length=50)),
                ('Property_Type_ID', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('District_ID', models.IntegerField()),
                ('Mobile', models.CharField(max_length=15)),
                ('Property_ID', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Area', models.IntegerField()),
                ('Bed_Room', models.IntegerField()),
                ('Bath_Room', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('Installment_Rate', models.FloatField()),
                ('Avatar', models.TextField()),
                ('Album', models.TextField()),
                ('Property_Status_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_Service',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Service_ID', models.IntegerField()),
                ('Property_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_Status',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Property_Status_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Property_Type_Name', models.CharField(max_length=50)),
                ('Property_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Service_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
