# Generated by Django 4.2.7 on 2023-11-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Installment_Contract',
        ),
        migrations.DeleteModel(
            name='Property_Service',
        ),
        migrations.DeleteModel(
            name='Property_Status',
        ),
        migrations.DeleteModel(
            name='Property_Type',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
