# Generated by Django 4.2.7 on 2023-11-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_delete_account_delete_city_delete_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_contract',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
