# Generated by Django 4.2.7 on 2023-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_full_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_contract',
            name='Date_Of_Contract',
            field=models.DateField(auto_now_add=True),
        ),
    ]
