# Generated by Django 4.2.7 on 2023-11-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_full_contract_date_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_contract',
            name='Full_Contract_Code',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
