# Generated by Django 4.2.7 on 2023-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_full_contract_full_contract_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_contract',
            name='Date_Of_Contract',
            field=models.DateField(),
        ),
    ]
