# Generated by Django 4.2.7 on 2023-11-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_full_contract_date_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='Property_Code',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
