# Generated by Django 4.2.7 on 2023-11-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_property_id_alter_property_property_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Property_Code',
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
    ]
