# Generated by Django 4.2.7 on 2023-11-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='homepage.full_contract'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='property',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='homepage.property'),
        ),
    ]
