# Generated by Django 4.2.7 on 2023-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_invoice_contract_invoice_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Album',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
